# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2
project_name: once
report_sizes: true
metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
builds:
  - main: ./cmd/once
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      ## <<Stencil::Block(onceLdflags)>>
      - -X main.Version={{ .Version }}
      ## <</Stencil::Block>>
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      ## <<Stencil::Block(onceExtraArch)>>

      ## <</Stencil::Block>>
    goos:
      - linux
      - darwin
      - windows
      ## <<Stencil::Block(onceExtraOS)>>

      ## <</Stencil::Block>>
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: "{{ .CommitTimestamp }}"
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: git
release:
  prerelease: "auto"
  footer: |-
    **Full Changelog**: https://github.com/jaredallard/once/compare/{{ .PreviousTag }}...{{ .Tag }}

## <<Stencil::Block(extraReleaseOpts)>>
brews:
  - commit_author:
      name: GitHub Actions
      email: 41898282+github-actions[bot]@users.noreply.github.com
    homepage: https://github.com/jaredallard/once
    license: GPL-3.0
    description: "Safely run commands concurrently that do not support it natively"
    repository:
      owner: jaredallard
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
## <</Stencil::Block>>
